export const STRINGS = {
  BASE_PATH: "/",
  HOME_PATH: "/home",
  DASHBOARD_PATH: "/dashboard",
  ASSETS_PATH: "/assets",
  ASSET_UPLOAD_PATH: "/assets/upload/new",
  USERS_PATH: "/users",
  INVITE_RESTAURANTS_PATH: "/invite-restaurants",
  NEW_ASSET_MODEL_UPLOAD_PATH: "/assets/model/new",
  PROFILE_PATH: "/profile",
  ASSET_ONBOARDING_PATH: "/asset-onboarding",
  ASSET_ONBOARDING_UPLOAD_PATH: "/asset-onboarding/upload",
  ASSET_ONBOARDING_DETAILS_ID_PATH: "/asset-onboarding/details/:id",
  ASSET_ONBOARDING_DETAILS_PATH: "/asset-onboarding/details",
  HOME: "Home",
  DASHBOARD: "Dashboard",
  ASSETS: "Assets",
  USERS: "Users",
  INVITE_RESTAURANTS: "Invite Restaurants",
  NEW_ASSETS_UPLOAD: "Add new assets",
  ASSET_NAME: "Asset name",
  ASSET_DETAILS: "Asset details",
  ASSET_DESCRIPTION: "Asset description",
  ASSET_PRICE: "Asset price",
  ASSET_TAGS: "Asset tags",
  ASSET_FILES: "Asset model files",
  ASSET_CATEGORIES: "Asset categories",
  INR: "indian Rupee",
  USD: "US Dollar",
  EUR: "Euro",
  REQUIRED_NAME: "Asset name is required",
  REQUIRED_DESCRIPTION: "Asset description is required",
  REQUIRED_PRICE: "Asset price is required",
  REQUIRED_CURRENCY: "Asset currency is required",
  REQUIRED_TAGS: "Asset tags are required",
  errorMessage: {
    validPrice: "Please enter a valid price"
  }
};
